### ISSUE TITLE
feature request: record not only audio input but also output

### ISSUE THREAD

**Issue by treakiandroid** [vijai1996/screenrecorder#48] opened 2018-03-14 09:11 UTC
I would like ro record full a/v device output instead only v output and a input. So i would need a special loopback cable to recordvoutput an i had bad quality do to a/d and d/a conversion and on the most devices get only mono audio do to lack of stereo input. Or i would need another device (which would ironically be esier than soldering et a special loopback cable together...)

If guess the android api suppprts it just like streaming a/v to some hardware (mirrorcast often called, or that undocumented Chromecast stuff)

So it would be possible i assume to do it entyerly in software...

THANKS A LOT

**Comment by vijai1996** [comment] 2018-03-14 09:29
Duplicate of #4 and #23

**Closed by vijai1996** 2018-03-14 09:29 UTC
