### ISSUE TITLE
Bug found in ScreenCam. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [vijai1996/screenrecorder#44] opened 2018-03-04 20:56 UTC
#### Expected behavior
When I downloaded this app I worked on it for 10- 20 mins then I want to change the saving location of the recording video.

#### Actual behavior
When i tried to change saving location of the video it brings me to home screen.
I tried several times but i t always brings me to home screen.

#### How to reproduce
Download the ScreenCam app from f-droid or play store.

Then open app, it shows some features,
Also it shows save location option.
Then click on it.
Finally it brings us to home screen.

* Browser: ScreenCam
* version:1.8.5
* Operating system:5.1.1
#### Recording Of The Bug
Here is the GIF of the bug.    
![20180304_210107.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520190572/jzrtiizkeuvphia7ofut.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/6zfzsr-bug-found-in-screencam">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by vijai1996** [comment] 2018-03-06 06:52
I'm not able to reproduce the bug on any of my phones/emulators. Can you try on a different phone and confirm if you still get the same result?

**Comment by PeerzadaZeeshan** [comment] 2018-03-06 07:10
I used this app on oppoa37f
Version:5.1.1
Several times I also tried but it always happens.

**Comment by vijai1996** [comment] 2018-03-06 13:25
Can you try on different phone? I cannot reproduce the bug on phones/emulators I have

**Comment by 0xpr03** [comment] 2018-03-28 13:06
@vijai1996 please just close it if you think it's too minor. The reporting account is 24 days old and posts only kind of abuse related issues to android repos (10+), all of them related to utopian, from which I've some response.

**Comment by vijai1996** [comment] 2018-03-28 13:15
@0xpr03 Thanks for letting me know.

**Closed by vijai1996** 2018-03-28 13:15 UTC
